Neural Network on Iris Dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import confusion_matrix, adjusted_rand_score
from scipy.optimize import linear_sum_assignment
from scipy.cluster.hierarchy import linkage,dendrogram
from sklearn.model_selection import train_test_split

df = pd.read_csv("Iris - Copy.csv")
df.dropna()

def relu(x):
    return np.maximum(0,x)

def drelu(x):
    return x>0

def soft_max(x):
    return np.exp(x) / np.sum(np.exp(x))

def loss_func():
    return 0

X = df.iloc[:,1:5].values

species_map = {
    "Iris-setosa": 0,
    "Iris-versicolor":1,
    "Iris-virginica":2,
}

y = df.iloc[:,-1].map(species_map).values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

num_classes = 3
Y = np.eye(num_classes)[y]

np.random.seed(42)

W1 = np.random.randn(4,5)
b1 = np.zeros((1,5))

W2 = np.random.randn(5,5)
b2 = np.zeros((1,5))

W3=  np.random.randn(5,5)
b3 = np.zeros((1,5))

W4 = np.random.randn(5,3)
b4 = np.zeros((1,3))

learning_rate = 0.01
epochs = 1

for epoch in range(epochs):
    #Forward Propogation

    Z1 = X@W1 + b1
    A1 = relu(Z1)

    Z2 = A1@W2 + b2
    A2 = relu(Z2)

    Z3 = A2@W3 + b3
    A3 = relu(Z3)

    Z4 = A3@W4 + b4
    final = soft_max(Z4)
    print(final)
    #loss= loss_func()

    #Back propogation

    dZ4 = (final - Y)/len(X)

    #weight updation
    #w1 = w1 -lr*(gr_w) 
    #b1 = b1 - lr*(gr_b)
    #w2 = w2 -lr*(gr_w) 
    #b2 = b2 - lr*(gr_b)
    #w3 = w3 -lr*(gr_w) 
    #b3 = b3 - lr*(gr_b)
    #w4 = w4 -lr*(gr_w) 
    #b4 = b4 - lr*(gr_b)
        #gradient found in back prop
    

[[1.79377544e-09 5.18833896e-05 9.81371296e-10]
 [2.24582813e-09 3.12476957e-05 9.08975222e-10]
 [2.07078014e-09 2.67601743e-05 1.14884292e-09]
 [2.19137669e-09 2.43357704e-05 1.10457347e-09]
 [1.72625833e-09 4.89232910e-05 1.08657530e-09]
 [1.48199834e-09 1.32818981e-04 7.67393131e-10]
 [1.90029450e-09 3.15680738e-05 1.20384461e-09]
 [1.88987539e-09 4.54444445e-05 9.72798649e-10]
 [2.40045396e-09 1.66816461e-05 1.18943519e-09]
 [2.17998635e-09 3.00948477e-05 9.78900742e-10]
 [1.62985625e-09 8.48626324e-05 8.56744468e-10]
 [1.91617857e-09 3.75336310e-05 1.06767493e-09]
 [2.27658029e-09 2.44532845e-05 1.03142955e-09]
 [2.30007114e-09 1.23315106e-05 1.53952191e-09]
 [1.38711218e-09 1.41592773e-04 8.26887864e-10]
 [1.16777977e-09 2.29374452e-04 8.27893839e-10]
 [1.45604876e-09 1.14299763e-04 8.67042765e-10]
 [1.77788657e-09 5.91326274e-05 9.19987008e-10]
 [1.53917915e-09 1.55359535e-04 6.53388292e-10]
 [1.56930677e-09 7.25502198e-05 1.00623141e-09]
 [1.87111013e-09 7.74133844e-05 7.147730