Neuron:

In [14]:
inp = [1.2,5.1,2.1]
weight = [3.1,2.1,8.7]
bias = 3

output = inp[0]*weight[0] +inp[1]*weight[1]+inp[2]*weight[2] +bias 
print(output)


35.7


In [6]:
inp = [1,2,3,2.5]
w1 = [0.2,0.8,-0.5,1]
w2 = [0.5,-0.91,0.26,-0.5]
w3 = [-0.26,-0.27,0.17,0.87]
b1 = 2
b2= 3
b3 = 0.5
output = []

out1 = inp[0]*w1[0]+inp[1]*w1[1]+inp[2]*w1[2]+inp[3]*w1[3]+b1
out2 = inp[0]*w2[0]+inp[1]*w2[1]+inp[2]*w2[2]+inp[3]*w2[3]+b2
out3 = inp[0]*w3[0]+inp[1]*w3[1]+inp[2]*w3[2]+inp[3]*w3[3]+b3
output = [out1,out2,out3]
print(output)

[4.8, 1.21, 2.385]


In [9]:
inp = [1,2,3,2.5]
weight = [[0.2,0.8,-0.5,1],
      [0.5,-0.91,0.26,-0.5],
      [-0.26,-0.27,0.17,0.87]]
bias = [2,3,0.5]
output_layer = []

for i in range(len(weight)):
    out = 0

    for j in range(len(inp)):
        out += inp[j] * weight[i][j]

    out += bias[i]
    output_layer.append(out)

print(output_layer)

[4.8, 1.21, 2.385]


In [ ]:
import numpy as np
inp = [1,2,3,2.5]
weight = [[0.2,0.8,-0.5,1],
      [0.5,-0.91,0.26,-0.5],
      [-0.26,-0.27,0.17,0.87]]
bias = [2,3,0.5]
output_layer = np.dot(weight,inp) + bias

print(output_layer)

[4.8   1.21  2.385]


transpose

In [2]:
import numpy as np
inp =np.array([[1,2,3,2.5],
       [1.2,5.1,2.1,3.2],
       [4.6,8.9,6.3,2.3]])
weight = np.array([[0.2,0.8,-0.5,1],
      [0.5,-0.91,0.26,-0.5],
      [-0.26,-0.27,0.17,0.87]])
bias = np.array([2,3,0.5])

output =np.dot(inp,weight.T) +bias

print(output)



[[ 4.8    1.21   2.385]
 [ 8.47  -2.095  1.952]
 [ 9.19  -2.311 -0.027]]


hidden layer

In [1]:
import numpy as np
inp =np.array([
      [1,2,3,2.5],
       [1.2,5.1,2.1,3.2],
       [4.6,8.9,6.3,2.3],
       [4.5,1.2,6.3,7.8]])

W1 = np.array([
      [0.2,0.8,-0.5,1],
      [0.5,-0.91,0.26,-0.5],
      [-0.26,-0.27,0.17,0.87],
      [0.3,-0.1,0.4,0.2],
      [-0.7,0.9,-0.3,0.5]])

b1 = np.array([2,3,0.5,1,-1.5])

W2 = np.array([
    [0.1,-0.2,0.3,0.4,-0.5],
    [-0.4,-0.5,-0.6,0.2,0.1]])
b2 = np.array([0.2,-0.1])

hidden = np.dot(inp,W1.T) + b1

print("hidden")
print(hidden)

output = np.dot(hidden,W2.T) + b2

print("output")
print(output)

hidden
[[ 4.8    1.21   2.385  2.8   -0.05 ]
 [ 8.47  -2.095  1.952  2.33   3.22 ]
 [ 9.19  -2.311 -0.027  4.47   2.55 ]
 [ 8.51   1.896  6.863  6.31  -1.56 ]]
output
[[ 2.2985 -3.501 ]
 [ 1.3736 -2.8237]
 [ 2.0861 -1.4553]
 [ 6.0347 -7.4638]]


In [5]:
import numpy as np

X = np.array([1, 2, 3, 2.5, 1.5])

W1 = np.random.randn(4, 5)
b1 = np.random.randn(4)

W2 = np.random.randn(3, 4)
b2 = np.random.randn(3)

W3 = np.random.randn(2, 3)
b3 = np.random.randn(2)

h1 = np.dot(W1, X) + b1
h2 = np.dot(W2, h1) + b2
output = np.dot(W3, h2) + b3

print("Input:",X)
print("Hidden Layer 1:",h1)
print("Hidden Layer 2:", h2)
print("Output:", output)

Input: [1.  2.  3.  2.5 1.5]
Hidden Layer 1: [-1.27735536  5.35300928  1.34970308  2.21345212]
Hidden Layer 2: [ 0.55888102 -1.58446735 -6.34442084]
Output: [-3.68707009 10.65370788]


Applying Activation Function

In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

def relu(x):
    return np.maximum(0,x)

def tanh(x):
    return np.tanh(x)

X = np.array([1, 2, 3, 2.5, 1.5])

W1 = np.random.randn(4, 5)
b1 = np.random.randn(4)

W2 = np.random.randn(3, 4)
b2 = np.random.randn(3)

W3 = np.random.randn(2, 3)
b3 = np.random.randn(2)

h1 = np.dot(W1, X) + b1
h1_output = relu(h1)

h2 = np.dot(W2, h1) + b2
h2_output = relu(h2)

output = np.dot(W3, h2) + b3
final = sigmoid(output)

print("Input:",X)
print("Hidden Layer 1:",h1)
print("Final Hidden Layer 1: ", h1_output)
print("Hidden Layer 2:", h2)
print("Final Hidden Layer 2: ",h2_output)
print("Output:", output)
print("Final Output: ",final)

Input: [1.  2.  3.  2.5 1.5]
Hidden Layer 1: [ 0.33229734  4.83682254 -2.83641118 -2.81098908]
Final Hidden Layer 1:  [0.33229734 4.83682254 0.         0.        ]
Hidden Layer 2: [ 2.92460555  3.58188157 -3.85479556]
Final Hidden Layer 2:  [2.92460555 3.58188157 0.        ]
Output: [ 1.30343096 -0.58134878]
Final Output:  [0.78641184 0.3586223 ]


Applying Activation Functions using Scikit-Learn

In [ ]:
import numpy as np
from sklearn.neural_network import MLPClassifier,MLPRegressor

X = np.array([1, 2, 3, 2.5, 1.5])

model = MLPRegressor(
    hidden_layer_sizes=(5,5),
    activation="relu",
    solver="adam",
    random_state=42
)

print(model)

MLPRegressor(hidden_layer_sizes=(5, 5), random_state=42)
